name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd ciphers_project
          python manage.py test
      - name: Build and push the image
        run: |
          docker login --username jts2052 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/jts2052/ciphers_project:latest --file Dockerfile .
          docker push ghcr.io/jts2052/ciphers_project:latest
